<?php

$filmes = [
  novoFilme("A Paixão de Cristo", "imagens/Paixão de Cristo.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, nihil. Illum pariatur labore accusantium consequuntur adipisci id excepturi repudiandae voluptates ratione recusandae, atque nesciunt odio. Aut, quidem eveniet? Corrupti ipsa doloribus, debitis dolorem illum, error excepturi fugiat natus aliquid nulla similique ut, molestias quam quia? Veniam illum voluptas veritatis fugit ea quas odit ad perspiciatis unde, cum consequuntur officiis eaque mollitia! Animi velit mollitia excepturi quo odio, odit molestias libero illum dolor est quis atque ut quam non aperiam quibusdam deleniti sapiente molestiae officiis dolorem? Numquam voluptatum, voluptatem perspiciatis cum molestiae magni illo? Non dignissimos libero quos labore impedit eum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati alias reiciendis iusto tempora commodi eos qui dolores? Fugiat, quisquam.
"),
  novoFilme("Bob Esponja", "imagens/Sponge Bob.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, nihil. Illum pariatur labore accusantium consequuntur adipisci id excepturi repudiandae voluptates ratione recusandae, atque nesciunt odio. Aut, quidem eveniet? Corrupti ipsa doloribus, debitis dolorem illum, error excepturi fugiat natus aliquid nulla similique ut, molestias quam quia? Veniam illum voluptas veritatis fugit ea quas odit ad perspiciatis unde, cum consequuntur officiis eaque mollitia! Animi velit mollitia excepturi quo odio, odit molestias libero illum dolor est quis atque ut quam non aperiam quibusdam deleniti sapiente molestiae officiis dolorem? Numquam voluptatum, voluptatem perspiciatis cum molestiae magni illo? Non dignissimos libero quos labore impedit eum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati alias reiciendis iusto tempora commodi eos qui dolores? Fugiat, quisquam.
"),
  novoFilme("Os Vingadores", "imagens/Avengers.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, nihil. Illum pariatur labore accusantium consequuntur adipisci id excepturi repudiandae voluptates ratione recusandae, atque nesciunt odio. Aut, quidem eveniet? Corrupti ipsa doloribus, debitis dolorem illum, error excepturi fugiat natus aliquid nulla similique ut, molestias quam quia? Veniam illum voluptas veritatis fugit ea quas odit ad perspiciatis unde, cum consequuntur officiis eaque mollitia! Animi velit mollitia excepturi quo odio, odit molestias libero illum dolor est quis atque ut quam non aperiam quibusdam deleniti sapiente molestiae officiis dolorem? Numquam voluptatum, voluptatem perspiciatis cum molestiae magni illo? Non dignissimos libero quos labore impedit eum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati alias reiciendis iusto tempora commodi eos qui dolores? Fugiat, quisquam.
"),
  novoFilme("Homem de Aço", "imagens/Superman.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, nihil. Illum pariatur labore accusantium consequuntur adipisci id excepturi repudiandae voluptates ratione recusandae, atque nesciunt odio. Aut, quidem eveniet? Corrupti ipsa doloribus, debitis dolorem illum, error excepturi fugiat natus aliquid nulla similique ut, molestias quam quia? Veniam illum voluptas veritatis fugit ea quas odit ad perspiciatis unde, cum consequuntur officiis eaque mollitia! Animi velit mollitia excepturi quo odio, odit molestias libero illum dolor est quis atque ut quam non aperiam quibusdam deleniti sapiente molestiae officiis dolorem? Numquam voluptatum, voluptatem perspiciatis cum molestiae magni illo? Non dignissimos libero quos labore impedit eum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati alias reiciendis iusto tempora commodi eos qui dolores? Fugiat, quisquam.
"),
  novoFilme("Toy Story", "imagens/Toy Story.jpg", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, nihil. Illum pariatur labore accusantium consequuntur adipisci id excepturi repudiandae voluptates ratione recusandae, atque nesciunt odio. Aut, quidem eveniet? Corrupti ipsa doloribus, debitis dolorem illum, error excepturi fugiat natus aliquid nulla similique ut, molestias quam quia? Veniam illum voluptas veritatis fugit ea quas odit ad perspiciatis unde, cum consequuntur officiis eaque mollitia! Animi velit mollitia excepturi quo odio, odit molestias libero illum dolor est quis atque ut quam non aperiam quibusdam deleniti sapiente molestiae officiis dolorem? Numquam voluptatum, voluptatem perspiciatis cum molestiae magni illo? Non dignissimos libero quos labore impedit eum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati alias reiciendis iusto tempora commodi eos qui dolores? Fugiat, quisquam.
")
];

?>